
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniH.js
 */

#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

namespace facebook::react {

/**
 * JNI C++ class for module 'NativeAdsModule'
 */
class JSI_EXPORT NativeAdsModuleSpecJSI : public JavaTurboModule {
public:
  NativeAdsModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativeCacheModule'
 */
class JSI_EXPORT NativeCacheModuleSpecJSI : public JavaTurboModule {
public:
  NativeCacheModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativeCastModule'
 */
class JSI_EXPORT NativeCastModuleSpecJSI : public JavaTurboModule {
public:
  NativeCastModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativeContentProtectionModule'
 */
class JSI_EXPORT NativeContentProtectionModuleSpecJSI : public JavaTurboModule {
public:
  NativeContentProtectionModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativeEventBroadcastModule'
 */
class JSI_EXPORT NativeEventBroadcastModuleSpecJSI : public JavaTurboModule {
public:
  NativeEventBroadcastModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativePlaybackSettingsModule'
 */
class JSI_EXPORT NativePlaybackSettingsModuleSpecJSI : public JavaTurboModule {
public:
  NativePlaybackSettingsModuleSpecJSI(const JavaTurboModule::InitParams &params);
};

/**
 * JNI C++ class for module 'NativePlayerModule'
 */
class JSI_EXPORT NativePlayerModuleSpecJSI : public JavaTurboModule {
public:
  NativePlayerModuleSpecJSI(const JavaTurboModule::InitParams &params);
};


JSI_EXPORT
std::shared_ptr<TurboModule> rntheo_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params);

} // namespace facebook::react
