
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public abstract class NativePlayerModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "THEORCTPlayerModule";

  public NativePlayerModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void version(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setAutoplay(double tag, boolean autoplay);

  @ReactMethod
  @DoNotStrip
  public abstract void setPreload(double tag, String type);

  @ReactMethod
  @DoNotStrip
  public abstract void setCurrentTime(double tag, double seekTime);

  @ReactMethod
  @DoNotStrip
  public abstract void setPipConfig(double tag, ReadableMap config);

  @ReactMethod
  @DoNotStrip
  public abstract void setBackgroundAudioConfig(double tag, ReadableMap config);

  @ReactMethod
  @DoNotStrip
  public abstract void setPresentationMode(double tag, String mode);

  @ReactMethod
  @DoNotStrip
  public abstract void setMuted(double tag, boolean muted);

  @ReactMethod
  @DoNotStrip
  public abstract void setPlaybackRate(double tag, double rate);

  @ReactMethod
  @DoNotStrip
  public abstract void setSelectedAudioTrack(double tag, @Nullable Double trackUid);

  @ReactMethod
  @DoNotStrip
  public abstract void setSelectedVideoTrack(double tag, @Nullable Double trackUid);

  @ReactMethod
  @DoNotStrip
  public abstract void setSelectedTextTrack(double tag, @Nullable Double trackUid);

  @ReactMethod
  @DoNotStrip
  public abstract void setSource(double tag, ReadableMap source);

  @ReactMethod
  @DoNotStrip
  public abstract void setTargetVideoQuality(double tag, ReadableArray qualities);

  @ReactMethod
  @DoNotStrip
  public abstract void setVolume(double tag, double volume);

  @ReactMethod
  @DoNotStrip
  public abstract void setAspectRatio(double tag, String ratio);

  @ReactMethod
  @DoNotStrip
  public abstract void setRenderingTarget(double tag, String target);

  @ReactMethod
  @DoNotStrip
  public abstract void setKeepScreenOn(double tag, boolean keepScreenOn);

  @ReactMethod
  @DoNotStrip
  public abstract void setPaused(double tag, boolean paused);

  @ReactMethod
  @DoNotStrip
  public abstract void setTextTrackStyle(double tag, ReadableMap style);

  @ReactMethod
  @DoNotStrip
  public abstract void setABRConfig(double tag, ReadableMap config);
}
