
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeCastModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "THEORCTCastModule";

  public NativeCastModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void casting(double tag, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastCasting(double tag, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void airplayCasting(double tag, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastState(double tag, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void airplayState(double tag, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastStart(double tag);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastStop(double tag);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastJoin(double tag);

  @ReactMethod
  @DoNotStrip
  public abstract void chromecastLeave(double tag);

  @ReactMethod
  @DoNotStrip
  public abstract void airplayStart(double tag);

  @ReactMethod
  @DoNotStrip
  public abstract void airplayStop(double tag);
}
