
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeCacheModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "THEORCTCacheModule";

  public NativeCacheModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void createTask(ReadableMap source, ReadableMap parameters, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getInitialState(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void renewLicense(String taskId, ReadableMap drmConfig);

  @ReactMethod
  @DoNotStrip
  public abstract void pauseCachingTask(String taskId);

  @ReactMethod
  @DoNotStrip
  public abstract void removeCachingTask(String taskId);

  @ReactMethod
  @DoNotStrip
  public abstract void startCachingTask(String taskId);
}
